apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: my-pipeline-
spec:
  pipelineRef:
    name: my-pipeline
  params:
  - name: repo-url
    value: https://github.com/MishaelRatemo/DjangoforProfessionals.git # https://dev.azure.com/ratemomishael/DevSecOps/_git/Hello-world   # https://github.com/leandronsp/chespirito.git
  - name: revision
    value: master
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  